### ISSUE TITLE
Commented + mx.ui.confim

### ISSUE THREAD

**Issue by nvwieren** [mendix/mx-check-deprecations#4]
Is it possible to skip commented lines? 
Additionally mx.ui.confirmation is still detected as a deprecated call to mx.ui.confirm; possibly due to the search for mx.ui.confirm in mx.ui.confirmation :)

Thanks

**Comment by JelteMX** [comment]
[v2](https://github.com/mendix/mx-check-deprecations/releases/tag/v2.0.0) released, this one skips comments
