### ISSUE TITLE
False positives on setAttribute and getAttribute

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/mx-check-deprecations#7]
In many widgets, there are false positive matches on the Element methods setAttribute and getAttribute.

https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

Is there a way to prevent those matches?

**Comment by JelteMX** [comment]
Not to my knowledge. You would need to figure out what kind of object it is. That's why there are disclaimers and the deprecation checker will tell you it is a **possible** deprecation. The ``match`` field will give you the ability to check if it is a false positive

**Comment by JelteMX** [comment]
v2 will report it like this:

```text
 location:    line: 112, column: 14
 deprecation: mendix.lib.MxObject#setAttribute || solution: mendix/lib/MxObject#set || version: 6
 match:       this.domNode.setAttribute("name", this.name);
 comment:     setAttribute is also used in HTML elements, this might be a false-positive.
```

**Comment by JelteMX** [comment]
[v2](https://github.com/mendix/mx-check-deprecations/releases/tag/v2.0.0) released
