### ISSUE TITLE
Missing deprecation check for templatePath

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/mx-check-deprecations#8]
Starting from 6.10 `templatePath` is not working anymore on for phonegap with WK webview (iOS)

Use `templateString` instead. Load is via "dojo/text!PathToTemplate/WidgetName.html"

Please add it to the deprecation list.

Thanks

**Comment by JelteMX** [comment]
I have been working on [v2](https://github.com/mendix/mx-check-deprecations/tree/v2) yesterday, refactored the deprecation checker. Will add this to the list of deprecations as well, plus start creating the mendix 7 deprecations list

**Comment by JelteMX** [comment]
v2 will report it like this:

```text
 RichText/widget/SimpleRichTextEditor.js results:

 location:    line: 74, column: 2
 deprecation: templatePath || solution: templateString with "dojo/text!" || version: 6
 match:       templatePath: dojo.moduleUrl("RichText", "widget/templates/RichTextEditor.html"),
 comment:     From 6.10 templatePath is not working anymore in Phonegap
```

**Comment by JelteMX** [comment]
[v2](https://github.com/mendix/mx-check-deprecations/releases/tag/v2.0.0) released
